### ISSUE TITLE
frog should arrive in an empty space

### ISSUE THREAD

**Issue by ebaudet** [tnicolas42/bomberman#123]
`EnemyFrog` ne doit se déplacer que quand il a un espace pour arriver qui est disponible.
Il ne peut pas arriver sur un mur.

**Comment by timnicolas** [comment]
normalement c'est deja le cas

tu est sur que ca marche pas ?

**Comment by timnicolas** [comment]
ah ouai t'as raison, faudra que je regarde, ca doit etre avec ma mise a jour de move
