### ISSUE TITLE
enemies counter bug

### ISSUE THREAD

**Issue by timnicolas** [tnicolas42/bomberman#145]
j'ai l'impression que quand on tue un enemie et que, pendant son animation de mort on finish le level, l'enemie n'est pas compté...
@ebaudet

**Comment by zer0nim** [comment]
Ah c'est peux être un peu de ma faute, avec les animations de mort j'attend la fin de l'anim de mort pour detruire l'objet.

```cpp
void	AEnemy::animEndCb(std::string animName) {
	if (animName == "Armature|death") {
		_animDeathEnd = true;
	}
	...
```

```
bool	AEnemy::postUpdate() {
	if (!active && (_animDeathEnd || !_model)) {
		delete this;
		return false;
	}

	return _postUpdate();
}
```

Dans `addBonusEnemies` faudrais aussi retirer les `!alive` de `enemies.size()` pour corriger ça.

**Comment by timnicolas** [comment]
je te laisse faire ca du coup ?

**Comment by zer0nim** [comment]
Comme tu veux mais je pourais pas le faire maintenant j'ai encore pleins de models à faire.
Il suffit juste de prendre en compte les enemie qui sont encore dans `enemies` mais qui ont `!alive`.

**Comment by timnicolas** [comment]
Ok
