### ISSUE TITLE
Simple end screen when all levels are finished

### ISSUE THREAD

**Issue by zer0nim** [tnicolas42/bomberman#150]
Like when we win, multiples models animations dancing
With credit (devs names, copyrighted music authors, ...)

**Comment by timnicolas** [comment]
en fait on a quoi a mettre ici a part nos 4 noms ?

**Comment by zer0nim** [comment]
pour l'instant rien, on peux mettre le titre du jeu en gros avec une belle police et une phrase genre "Thank's you for playing"

**Comment by zer0nim** [comment]
Un recap des scores sinon mais pas obligé
