### ISSUE TITLE
Handle error for normal users

### ISSUE THREAD

**Issue by ebaudet** [tnicolas42/bomberman#158]
Gérer les erreurs de `SceneManager::run()` ou `update()` ou `draw()` retourne `false` en quittant proprement et en affichant l'erreur sur une modale système avec le message d'erreur.

De manière à avoir une compréhension de pourquoi le programme à quitté quand on ne le lance pas depuis une console.

**Comment by timnicolas** [comment]
maybe with this https://wiki.libsdl.org/SDL_ShowSimpleMessageBox
