### ISSUE TITLE
Show info of bonus taken

### ISSUE THREAD

**Issue by ebaudet** [tnicolas42/bomberman#169]
Afficher les infos des bonus pris en `SceneCheatCode->loginfo()` afin de mieux comprendre ce que c'est, et clear le reste des commande avant pour ne pas surcharger l'affichage.

ex. :
`Bonus Passe Flame: the bombs doesn't affect you anymore.`

**Comment by timnicolas** [comment]
plutot utiliser `logInfoScreen` (define)
