### ISSUE TITLE
Move camera acording to level size

### ISSUE THREAD

**Issue by zer0nim** [tnicolas42/bomberman#184]
Move camera acording to level size
![image](https://user-images.githubusercontent.com/13215654/80644186-8b361d00-8a69-11ea-9ab9-b8953fe05356.png)

**Comment by timnicolas** [comment]
@zer0nim 
par contre il y a aussi des arbres sur le terrain, on fait quoi pour ca ? Possible de les enlever ?

**Comment by zer0nim** [comment]
oui j'enleverais ceux qui gene, normalement ebaudet devrais aussi decaller un peu le terrain a gauche

**Comment by timnicolas** [comment]
ok parfait

**Comment by zer0nim** [comment]
@tnicolas42 si tu merge master tu auras le nouveau terrain plus plat avec moins d'arbres, faudras surement le decaler un peu pour qu'il soit bien centré
