### ISSUE TITLE
Impossible to quit game during intro of level

### ISSUE THREAD

**Issue by ebaudet** [tnicolas42/bomberman#196]
Lors de la scène d'intro, si on veut quitter avec cmd+q, on a bien le menu pour quitter, et qu'on choisit de quitter, ça prends du temps avant de quitter (sûrement le temps de finir l'animation)

**Comment by timnicolas** [comment]
j'ai fait pas mal de tests et le temps pour quit est pas plus long dans l'intro
par contre c'est long de fermer le jeu (unload toute les ressources)
@ebaudet Si t'es OK, on peut close l'issue
