### ISSUE TITLE
Sometime the cursor is hidden at startup in the menu

### ISSUE THREAD

**Issue by zer0nim** [tnicolas42/bomberman#202]

**Comment by timnicolas** [comment]
@zer0nim tu saurais me dire un peu quand est ce que ca arrive ?
@ebaudet ca t'arrive aussi ?

**Comment by zer0nim** [comment]
C'est vraiment random, parfois quand je lance le jeu la souris est en mode fps, ça doit arriver une fois sur 100

**Comment by timnicolas** [comment]
ah ouai
bah je vais essayer de comprendre pourquoi du coup

**Comment by ebaudet** [comment]
Peut être lié en full screen des faut cliquer 2 fois sur les boutons sinon ça marche pas

**Comment by timnicolas** [comment]
ouai ca par contre j'ai deja eu

**Comment by zer0nim** [comment]
Je suis même pas en full screen, c'est juste que le curseur ne s'affiche pas, comme en mode camera fps mais du coup dans les menus c'est pas pratique, mais c'est rare donc si tu trouve pas d'où ça viens pg

**Comment by timnicolas** [comment]
ouai bah du coup j'ai changé quelques trucs, je sais pas si ca marche maintenant mais peut etre
