### ISSUE TITLE
Change default key actions

### ISSUE THREAD

**Issue by ebaudet** [tnicolas42/bomberman#208]
- Quand on fait pause, on tape <kbd>esc</kbd>, c'est plus logique de quitter le menu avec la même touche que de quitter le jeu.

- La touche action est plus logique pour faire passer l'intro et l'outro que <kbd>enter</kbd>

**Comment by timnicolas** [comment]
j'ai pas compris le premier point

`esc` pour mettre en pause puis `esc` pour remettre en play ?

**Comment by ebaudet** [comment]
Oui, ça me paraît plus logique
