### ISSUE TITLE
Remove french in the code, for example `Player::BonusActifs`

### ISSUE THREAD

**Issue by zer0nim** [tnicolas42/bomberman#213]

**Comment by timnicolas** [comment]
je voit pas ou ils sont les comments en francais

**Comment by zer0nim** [comment]
Je sais pas si il y en as d'autres, je disais ça parce que j'ai vu `Player::BonusActifs`, faut juste vérifier qu'il y en ai pas d'autres

**Comment by timnicolas** [comment]
ah c'est bon j'ai vu
je trouvais pas, je faisais un find `Player::BonusActifs` mais il n'y a jamais cette string
