### ISSUE TITLE
Create transparent app icon png

### ISSUE THREAD

**Issue by zer0nim** [tnicolas42/bomberman#223]
Replace app icon: ![icon-app](https://user-images.githubusercontent.com/13215654/82240990-a5ae3880-993b-11ea-84d2-0b464efa129c.png)
with a new one with alpha background

**Comment by zer0nim** [comment]
Render with blender
https://blender.stackexchange.com/questions/1303/can-blender-render-pngs-with-the-background-transparent

Or photoshop:
https://www.youtube.com/watch?v=Li5s0WMVbtE

**Comment by timnicolas** [comment]
il faut aussi faire une image de max 200 de large et 55 de haut pour github pages (la meme de moins bonne qualité ?)

**Comment by zer0nim** [comment]
Oui on mettras la même je pense, un format caré c'est bon ?

**Comment by timnicolas** [comment]
oui je pense
