### ISSUE TITLE
JsonSettings emit warning for valid settings

### ISSUE THREAD

**Issue by guilhemSmith** [tnicolas42/bomberman#41]
A la lecture d'un fichier json, les doubles qui n'ont pas de valeur decimale émettent un warning:  
```
{
"audio": {
		"Master volume": 1,
		"Music volume": 0.9,
		"Sound volume": 0.9
	},
}
```
Au runtime:  
```
[WARN][srcs/utils/SettingsJson.cpp 132]: invalid setting type or name: Master volume
```

**Comment by timnicolas** [comment]
oui c'est normal.
Le truc de json considere que c'est un int.
Pour le moment, ne met que des doubles dans le json (1.0), je vais essayer de regler ce probleme plus tard

**Comment by guilhemSmith** [comment]
C'est pas un bug bloquant en soit, les valeurs sont tout de même récuperées correctement.  
J'ai juste préféré signaler le warning au cas où.
