### ISSUE TITLE
Make ui displayable in half to be able to show item at the bottom of the scrollbar

### ISSUE THREAD

**Issue by zer0nim** [tnicolas42/bomberman#94]
Make ui displayable in half to be able to show item at the bottom of the scrollbar
`gl_FragCoord`
https://learnopengl.com/Advanced-OpenGL/Advanced-GLSL

**Comment by timnicolas** [comment]
pour les UI, tu devra modifier:
- `TextRender`
- `ImageRender`
- le shader de rectangle

Il faudra aussi que tu modifie les conditions d'affichage des items 
https://github.com/tnicolas42/bomberman/blob/c646f271a2d2342497a3adfc63c4e3113faf3a22/srcs/utils/opengl/UI/ABaseUI.cpp#L72
En gros ca veux dire -> ne pas afficher si l'item est completement en dehors de l'ecran ou un peu en dehors de la scrollbar zone (faudra appeler `isTotallyOutOfMaster`)
